=== Kandimus/tritonn/xsd/kernel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ver="0.17" -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://tritonn.ru" xmlns="http://tritonn.ru" elementFormDefault="qualified">

<!--
  Тип BOOL
-->
<xs:simpleType name="type_bool">
      <xs:restriction base="xs:string">
        <xs:pattern value="true|false|1|0"/>
      </xs:restriction>
    </xs:simpleType>

<!--
  Элемент value
-->
<xs:element name="value">
  <xs:complexType>
    <xs:attribute name="name"     type="xs:string"  use="required"/>
    <xs:attribute name="type"     type="xs:string"  default=""/>
    <xs:attribute name="unit"     type="xs:string"  default="0"/>
    <xs:attribute name="readonly" type="type_bool"  default="1"/>
    <xs:attribute name="loadable" type="type_bool"  default="0"/>
    <xs:attribute name="access"   type="xs:string"  default="0"/>
  </xs:complexType>
</xs:element>
<!--
  Тип элементов перечисления элементов value
-->
<xs:complexType name="type_value">
  <xs:sequence>
    <xs:element ref="value"  minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<!--
  Элемент input
-->
<xs:element name="input">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="shadow"  minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name"   type="xs:string" use="required"/>
    <xs:attribute name="unit"   type="xs:string" use="required"/>
    <xs:attribute name="shadow" type="xs:string"/>
  </xs:complexType>
</xs:element>
<!--
  Тип элементов перечисления элементов input
-->
<xs:complexType name="type_input">
  <xs:sequence>
    <xs:element ref="input"  minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<!--
  Элемент output
-->
<xs:element name="output">
  <xs:complexType>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="unit" type="xs:string" use="required"/>
    <xs:attribute name="default" type="xs:string" use="optional"/>
  </xs:complexType>
</xs:element>
<!--
  Тип элементов перечисления элементов output
-->
<xs:complexType name="type_output">
  <xs:sequence>
    <xs:element ref="output"  minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<!--
  Тип элементов ios и objects
-->
<xs:complexType name="type_object">
  <xs:all>
    <xs:element name="values"  type="type_value"  minOccurs="1" maxOccurs="1"/>
    <xs:element name="inputs"  type="type_input"  minOccurs="0" maxOccurs="1"/>
    <xs:element name="outputs" type="type_output" minOccurs="0" maxOccurs="1"/>
  </xs:all>
  <xs:attribute name="name" type="xs:string" use="required"/>
  <xs:attribute name="global">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="true|false|1|0"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
</xs:complexType>

<!-- Тип сигнала IO для привязки к модулю -->
  
    
<!--
  Описательная часть
-->
  <xs:element name="kernel">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="sysvars" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="values"  type="type_value"  minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="io_list" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="io" type="type_object" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="objects" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="object" type="type_object" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="hardware" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="ver" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Kandimus/tritonn/docs/kernel.xml
<?xml version="1.0" encoding="UTF-8"?>
<kernel ver="0.18" xmlns="http://tritonn.ru" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tritonn.ru ./kernel.xsd">
<!--
	System variables
-->
<sysvars>
	<values>
		<value name="system.version.major" type="USINT" readonly="1" loadable="0" unit="512" access="0x80000000"/>
		<value name="system.version.minor" type="USINT" readonly="1" loadable="0" unit="512" access="0x80000000"/>
		<value name="system.version.build" type="UINT" readonly="1" loadable="0" unit="512" access="0x80000000"/>
		<value name="system.version.hash" type="UDINT" readonly="1" loadable="0" unit="512" access="0x80000000"/>
		<value name="system.version.crc" type="UDINT" readonly="1" loadable="0" unit="512" access="0x80000000"/>
		<value name="system.state.alarm" type="UDINT" readonly="1" loadable="0" unit="512" access="0x80000000"/>
		<value name="system.state.live" type="USINT" readonly="1" loadable="0" unit="512" access="0x80000000"/>
		<value name="system.state.rebootreason" type="USINT" readonly="1" loadable="0" unit="512" access="0x80000000"/>
		<value name="system.state.simulate" type="USINT" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="system.datetime.sec" type="INT" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="system.datetime.min" type="INT" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="system.datetime.hour" type="INT" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="system.datetime.day" type="INT" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="system.datetime.month" type="INT" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="system.datetime.year" type="INT" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="system.datetime.set.sec" type="INT" readonly="0" loadable="0" unit="512" access="0x00020000"/>
		<value name="system.datetime.set.min" type="INT" readonly="0" loadable="0" unit="512" access="0x00020000"/>
		<value name="system.datetime.set.hour" type="INT" readonly="0" loadable="0" unit="512" access="0x00020000"/>
		<value name="system.datetime.set.day" type="INT" readonly="0" loadable="0" unit="512" access="0x00020000"/>
		<value name="system.datetime.set.month" type="INT" readonly="0" loadable="0" unit="512" access="0x00020000"/>
		<value name="system.datetime.set.year" type="INT" readonly="0" loadable="0" unit="512" access="0x00020000"/>
		<value name="system.datetime.set.accept" type="INT" readonly="0" loadable="0" unit="512" access="0x00020000"/>
	</values>
</sysvars>

<!--
	Переменная
-->
<object name="var" global="true">
	<values>
		<value name="value" type="LREAL" readonly="0" loadable="0" unit="0" access="0x00000000"/>
		<value name="unit" type="STRID" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="lolo" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000200"/>
		<value name="lo" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000200"/>
		<value name="hi" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000200"/>
		<value name="hihi" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000200"/>
		<value name="hysteresis" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000200"/>
		<value name="status" type="UINT" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="setup" type="UINT" readonly="1" loadable="1" unit="512" access="0x00000200"/>
	</values>
	<inputs>
		<input name="value" unit="0"/>
	</inputs>
	<outputs>
		<output name="value" unit="0" default="1"/>
		<output name="fault" unit="512"/>
	</outputs>
</object>

<!-- 
	IO objects list 
-->
<io_list>
<!--
	Аналоговый сигнал
-->
<io name="ai">
	<values>
		<value name="present.value" type="LREAL" readonly="1" loadable="0" unit="0" access="0x00000000"/>
		<value name="present.unit" type="STRID" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="present.lolo" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000200"/>
		<value name="present.lo" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000200"/>
		<value name="present.hi" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000200"/>
		<value name="present.hihi" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000200"/>
		<value name="present.hysteresis" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000200"/>
		<value name="present.status" type="UINT" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="present.setup" type="UINT" readonly="1" loadable="1" unit="512" access="0x00000200"/>
		<value name="physical.value" type="LREAL" readonly="1" loadable="0" unit="0" access="0x00000000"/>
		<value name="physical.unit" type="STRID" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="physical.lolo" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000200"/>
		<value name="physical.lo" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000200"/>
		<value name="physical.hi" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000200"/>
		<value name="physical.hihi" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000200"/>
		<value name="physical.hysteresis" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000200"/>
		<value name="physical.status" type="UINT" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="physical.setup" type="UINT" readonly="1" loadable="1" unit="512" access="0x00000200"/>
		<value name="current.value" type="LREAL" readonly="1" loadable="0" unit="515" access="0x00000000"/>
		<value name="current.unit" type="STRID" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="current.lolo" type="LREAL" readonly="0" loadable="1" unit="515" access="0x00000200"/>
		<value name="current.lo" type="LREAL" readonly="0" loadable="1" unit="515" access="0x00000200"/>
		<value name="current.hi" type="LREAL" readonly="0" loadable="1" unit="515" access="0x00000200"/>
		<value name="current.hihi" type="LREAL" readonly="0" loadable="1" unit="515" access="0x00000200"/>
		<value name="current.hysteresis" type="LREAL" readonly="0" loadable="1" unit="515" access="0x00000200"/>
		<value name="current.status" type="UINT" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="current.setup" type="UINT" readonly="1" loadable="1" unit="512" access="0x00000200"/>
		<value name="keypad" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000800"/>
		<value name="scales.min" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000400"/>
		<value name="scales.max" type="LREAL" readonly="0" loadable="1" unit="0" access="0x00000400"/>
		<value name="setup" type="UINT" readonly="1" loadable="1" unit="512" access="0x80000000"/>
		<value name="mode" type="UINT" readonly="0" loadable="1" unit="512" access="0x00000800"/>
		<value name="status" type="UINT" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="fault" type="UDINT" readonly="1" loadable="0" unit="512" access="0x00000000"/>
	</values>
	<outputs>
		<output name="present" unit="0" default="1"/>
		<output name="physical" unit="0"/>
		<output name="current" unit="515"/>
		<output name="fault" unit="512"/>
	</outputs>
</io>
<!--
	Частотно-импульсный сигнал
-->
<io name="counter">
	<values>
		<value name="impulse.value" type="LREAL" readonly="1" loadable="0" unit="514" access="0x00000000"/>
		<value name="impulse.unit" type="STRID" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="impulse.lolo" type="LREAL" readonly="0" loadable="1" unit="514" access="0x00000200"/>
		<value name="impulse.lo" type="LREAL" readonly="0" loadable="1" unit="514" access="0x00000200"/>
		<value name="impulse.hi" type="LREAL" readonly="0" loadable="1" unit="514" access="0x00000200"/>
		<value name="impulse.hihi" type="LREAL" readonly="0" loadable="1" unit="514" access="0x00000200"/>
		<value name="impulse.hysteresis" type="LREAL" readonly="0" loadable="1" unit="514" access="0x00000200"/>
		<value name="impulse.status" type="UINT" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="impulse.setup" type="UINT" readonly="1" loadable="1" unit="512" access="0x00000200"/>
		<value name="frequency.value" type="LREAL" readonly="1" loadable="0" unit="192" access="0x00000000"/>
		<value name="frequency.unit" type="STRID" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="frequency.lolo" type="LREAL" readonly="0" loadable="1" unit="192" access="0x00000200"/>
		<value name="frequency.lo" type="LREAL" readonly="0" loadable="1" unit="192" access="0x00000200"/>
		<value name="frequency.hi" type="LREAL" readonly="0" loadable="1" unit="192" access="0x00000200"/>
		<value name="frequency.hihi" type="LREAL" readonly="0" loadable="1" unit="192" access="0x00000200"/>
		<value name="frequency.hysteresis" type="LREAL" readonly="0" loadable="1" unit="192" access="0x00000200"/>
		<value name="frequency.status" type="UINT" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="frequency.setup" type="UINT" readonly="1" loadable="1" unit="512" access="0x00000200"/>
		<value name="period.value" type="LREAL" readonly="1" loadable="0" unit="209" access="0x00000000"/>
		<value name="period.unit" type="STRID" readonly="1" loadable="0" unit="512" access="0x00000000"/>
		<value name="period.lolo" type="LREAL" readonly="0" loadable="1" unit="209" access="0x00000200"/>
		<value name="period.lo" type="LREAL" readonly="0" loadable="1" unit="209" access="0x00000200"/>
		<value name="period.hi" type="LREAL" readonly="0" loadable="1" unit="209" access="0x00000200"/>
		<value name="period.hihi" type="LREAL" readonly="0" loadable="1" unit="209" access="0x00000200"/>
