=== Kandimus/tritonn/xsd/systemtext.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ver="0.17" -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://tritonn.ru" xmlns="http://tritonn.ru" elementFormDefault="qualified">
<!--
  Описательная часть
-->
  <xs:element name="strings">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="lang" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="str" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="value" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="kernel" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Kandimus/tritonn/bin/systemtext.xml
<?xml version="1.0" encoding="utf-8"?>
<strings kernel="0.18" xmlns="http://tritonn.ru" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tritonn.ru ./systemtext.xsd">
	<lang value="ru">
		<str id="0"/>
		<!-- Температурные единицы измерения -->
		<str id="16">°C</str>
		<str id="17">К</str>
		<str id="18">F</str>
		<!-- Единицы измерения давления (избыточного) -->
		<str id="32">МПа</str>
		<str id="33">кПа</str>
		<str id="34">кгс/см²</str>
		<str id="35">бар</str>
		<str id="36">мбар</str>
		<str id="37">атм</str>
		<str id="38">мм рт. ст.</str>
		<str id="39">psi</str>
		<!-- Плотность -->
		<str id="48">кг/м³</str>
		<str id="49">г/см³</str>
		<!-- Вязкость динамическая -->
		<str id="64">сП</str>
		<str id="65">П</str>
		<str id="66">кгс·с/м²</str>
		<str id="67">Па·с</str>
		<!-- Вязкость кинематическая (динамическая деленная на плотность) -->
		<str id="80">сСт</str>
		<str id="81">Ст</str>
		<str id="82">м²/с</str>
		<!-- Масса -->
		<str id="96">т</str>
		<str id="97">кг</str>
		<!-- Объем -->
		<str id="112">м³</str>
		<str id="113">л</str>
		<!-- Расход массовый -->
		<str id="128">т/ч</str>
		<str id="129">кг/ч</str>
		<!-- Расход объемный -->
		<str id="144">м³/ч</str>
		<str id="145">л/ч</str>
		<!-- Коэф. расходомеров массовых -->
		<str id="160">имп/т</str>
		<str id="161">имп/кг</str>
		<!-- Коэф. расходомеров объемных -->
		<str id="176">имп/м³</str>
		<str id="177">имп/л</str>
		<!-- Частота -->
		<str id="192">Гц</str>
		<str id="193">кГц</str>
		<str id="194">МГц</str>
		<!-- Время -->
		<str id="208">нс</str>
		<str id="209">мкс</str>
		<str id="210">мс</str>
		<str id="211">с</str>
		<!-- 288-303 Резерв под Единицы измерения давления (атмосферного) -->
		
		<!-- -->
		<str id="512"/>            <!-- Безразмерная величина -->
		<str id="513">%</str>      <!-- Обычные проценты -->
		<str id="514">имп</str>
		<str id="515">мА</str>
		<str id="516">В</str>      <!-- Вольты -->
		<str id="517">C¯¹</str>    <!-- Коэф. объемного расширения, B -->
		<str id="518">МПа¯¹</str>  <!-- Коэф. сжимаемости, Y          -->
		<str id="519">% масс</str> <!-- Обводненность массовая        -->
		<str id="520">% об</str>   <!-- Обводненность объемная        -->
		<str id="521"/>            <!-- Коэф. плотнмера (солартрон)   -->
		
		<str id="1000">текущее значение</str> <!-- SID_PRESENT -->
		<str id="1001">физическое значение</str> <!-- SID_PHYSICAL -->
		<str id="1002">значение тока</str> <!-- SID_CURRENT -->
		<str id="1003">температура</str> <!-- SID_TEMPERATURE -->
		<str id="1004">давление</str> <!-- SID_PRESSURE -->
		<str id="1005">период</str> <!-- SID_PERIOD -->
		<str id="1006">плотность</str> <!-- SID_DENSITY -->
		<str id="1007">плотность при н.у.</str> <!-- SID_DENSITY15 -->
		<str id="1008">плотность при 20 °C</str> <!-- SID_DENSITY20 -->
		<str id="1009">коэфициент β</str> <!-- SID_B -->
		<str id="1010">коэфициент β при н.у.</str> <!-- SID_B15 -->
		<str id="1011">коэфициент γ</str> <!-- SID_Y -->
		<str id="1012">коэфициент γ при н.у.</str> <!-- SID_Y15 -->
		<str id="1013">коэфициент CTL</str> <!-- SID_CTL -->
		<str id="1014">коэфициент CPL</str> <!-- SID_CPL -->
		<str id="1015">импульс</str> <!-- SID_IMPULSE -->
		<str id="1016">частота</str> <!-- SID_FREQUENCY -->
		<str id="1017">расход массовый</str> <!-- SID_FLOWRATE_MASS -->
		<str id="1018">расход объемный</str> <!-- SID_FLOWRATE_VOLUME -->
		<str id="1019">расход объемный при н.у.</str> <!-- SID_FLOWRATE_VOLUME15 -->
		<str id="1020">расход объемный при 20 °C</str> <!-- SID_FLOWRATE_VOLUME20 -->

		<str id="1500">выходное значение</str> <!-- SID_SEL_OUT -->
		<str id="1501">входное значение 1</str> <!-- SID_SEL_IN1 -->
    <str id="1502">входное значение 2</str> <!-- SID_SEL_IN2 -->
    <str id="1503">входное значение 3</str> <!-- SID_SEL_IN3 -->
    <str id="1504">входное значение 4</str> <!-- SID_SEL_IN4 -->
    <str id="1505">флаг ошибки входа 1</str> <!-- SID_SEL_FLT1 -->
    <str id="1506">флаг ошибки входа 2</str> <!-- SID_SEL_FLT2 -->
    <str id="1507">флаг ошибки входа 3</str> <!-- SID_SEL_FLT3 -->
    <str id="1508">флаг ошибки входа 4</str> <!-- SID_SEL_FLT4 -->
    <str id="1509">группа 1, входное значение 1</str> <!-- SID_SEL_GRP1_IN1 -->
    <str id="1510">группа 1, входное значение 2</str> <!-- SID_SEL_GRP1_IN2 -->
    <str id="1511">группа 1, входное значение 3</str> <!-- SID_SEL_GRP1_IN3 -->
    <str id="1512">группа 1, входное значение 4</str> <!-- SID_SEL_GRP1_IN4 -->
    <str id="1513">группа 2, входное значение 1</str> <!-- SID_SEL_GRP2_IN1 -->
    <str id="1514">группа 2, входное значение 2</str> <!-- SID_SEL_GRP2_IN2 -->
    <str id="1515">группа 2, входное значение 3</str> <!-- SID_SEL_GRP2_IN3 -->
    <str id="1516">группа 2, входное значение 4</str> <!-- SID_SEL_GRP2_IN4 -->
    <str id="1517">группа 3, входное значение 1</str> <!-- SID_SEL_GRP3_IN1 -->
    <str id="1518">группа 3, входное значение 2</str> <!-- SID_SEL_GRP3_IN2 -->
    <str id="1519">группа 3, входное значение 3</str> <!-- SID_SEL_GRP3_IN3 -->
    <str id="1520">группа 3, входное значение 4</str> <!-- SID_SEL_GRP3_IN4 -->
    <str id="1521">группа 4, входное значение 1</str> <!-- SID_SEL_GRP4_IN1 -->
    <str id="1522">группа 4, входное значение 2</str> <!-- SID_SEL_GRP4_IN2 -->
    <str id="1523">группа 4, входное значение 3</str> <!-- SID_SEL_GRP4_IN3 -->
    <str id="1524">группа 4, входное значение 4</str> <!-- SID_SEL_GRP4_IN4 -->
    <str id="1525">группа 5, входное значение 1</str> <!-- SID_SEL_GRP5_IN1 -->
    <str id="1526">группа 5, входное значение 2</str> <!-- SID_SEL_GRP5_IN2 -->
    <str id="1527">группа 5, входное значение 3</str> <!-- SID_SEL_GRP5_IN3 -->
    <str id="1528">группа 5, входное значение 4</str> <!-- SID_SEL_GRP5_IN4 -->
    <str id="1529">группа 6, входное значение 1</str> <!-- SID_SEL_GRP6_IN1 -->
    <str id="1530">группа 6, входное значение 2</str> <!-- SID_SEL_GRP6_IN2 -->
    <str id="1531">группа 6, входное значение 3</str> <!-- SID_SEL_GRP6_IN3 -->
    <str id="1532">группа 6, входное значение 4</str> <!-- SID_SEL_GRP6_IN4 -->
    <str id="1533">группа 7, входное значение 1</str> <!-- SID_SEL_GRP7_IN1 -->
    <str id="1534">группа 7, входное значение 2</str> <!-- SID_SEL_GRP7_IN2 -->
    <str id="1535">группа 7, входное значение 3</str> <!-- SID_SEL_GRP7_IN3 -->
    <str id="1536">группа 7, входное значение 4</str> <!-- SID_SEL_GRP7_IN4 -->
    <str id="1537">группа 8, входное значение 1</str> <!-- SID_SEL_GRP8_IN1 -->
    <str id="1538">группа 8, входное значение 2</str> <!-- SID_SEL_GRP8_IN2 -->
    <str id="1539">группа 8, входное значение 3</str> <!-- SID_SEL_GRP8_IN3 -->
    <str id="1540">группа 8, входное значение 4</str> <!-- SID_SEL_GRP8_IN4 -->
    <str id="1541">группа 1, флаг ошибки входа 1</str> <!-- SID_SEL_GRP1_FLT1 -->
    <str id="1542">группа 1, флаг ошибки входа 2</str> <!-- SID_SEL_GRP1_FLT2 -->
    <str id="1543">группа 1, флаг ошибки входа 3</str> <!-- SID_SEL_GRP1_FLT3 -->
    <str id="1544">группа 1, флаг ошибки входа 4</str> <!-- SID_SEL_GRP1_FLT4 -->
    <str id="1545">группа 2, флаг ошибки входа 1</str> <!-- SID_SEL_GRP2_FLT1 -->
    <str id="1546">группа 2, флаг ошибки входа 2</str> <!-- SID_SEL_GRP2_FLT2 -->
    <str id="1547">группа 2, флаг ошибки входа 3</str> <!-- SID_SEL_GRP2_FLT3 -->
    <str id="1548">группа 2, флаг ошибки входа 4</str> <!-- SID_SEL_GRP2_FLT4 -->
    <str id="1549">группа 3, флаг ошибки входа 1</str> <!-- SID_SEL_GRP3_FLT1 -->
    <str id="1550">группа 3, флаг ошибки входа 2</str> <!-- SID_SEL_GRP3_FLT2 -->
    <str id="1551">группа 3, флаг ошибки входа 3</str> <!-- SID_SEL_GRP3_FLT3 -->
    <str id="1552">группа 3, флаг ошибки входа 4</str> <!-- SID_SEL_GRP3_FLT4 -->
    <str id="1553">группа 4, флаг ошибки входа 1</str> <!-- SID_SEL_GRP4_FLT1 -->
    <str id="1554">группа 4, флаг ошибки входа 2</str> <!-- SID_SEL_GRP4_FLT2 -->
    <str id="1555">группа 4, флаг ошибки входа 3</str> <!-- SID_SEL_GRP4_FLT3 -->
    <str id="1556">группа 4, флаг ошибки входа 4</str> <!-- SID_SEL_GRP4_FLT4 -->
    <str id="1557">группа 5, флаг ошибки входа 1</str> <!-- SID_SEL_GRP5_FLT1 -->
    <str id="1558">группа 5, флаг ошибки входа 2</str> <!-- SID_SEL_GRP5_FLT2 -->
    <str id="1559">группа 5, флаг ошибки входа 3</str> <!-- SID_SEL_GRP5_FLT3 -->
    <str id="1560">группа 5, флаг ошибки входа 4</str> <!-- SID_SEL_GRP5_FLT4 -->
    <str id="1561">группа 6, флаг ошибки входа 1</str> <!-- SID_SEL_GRP6_FLT1 -->
    <str id="1562">группа 6, флаг ошибки входа 2</str> <!-- SID_SEL_GRP6_FLT2 -->
    <str id="1563">группа 6, флаг ошибки входа 3</str> <!-- SID_SEL_GRP6_FLT3 -->
    <str id="1564">группа 6, флаг ошибки входа 4</str> <!-- SID_SEL_GRP6_FLT4 -->
    <str id="1565">группа 7, флаг ошибки входа 1</str> <!-- SID_SEL_GRP7_FLT1 -->
    <str id="1566">группа 7, флаг ошибки входа 2</str> <!-- SID_SEL_GRP7_FLT2 -->
    <str id="1567">группа 7, флаг ошибки входа 3</str> <!-- SID_SEL_GRP7_FLT3 -->
    <str id="1568">группа 7, флаг ошибки входа 4</str> <!-- SID_SEL_GRP7_FLT4 -->
    <str id="1569">группа 8, флаг ошибки входа 1</str> <!-- SID_SEL_GRP8_FLT1 -->
    <str id="1570">группа 8, флаг ошибки входа 2</str> <!-- SID_SEL_GRP8_FLT2 -->
    <str id="1571">группа 8, флаг ошибки входа 3</str> <!-- SID_SEL_GRP8_FLT3 -->
		<str id="1572">группа 8, флаг ошибки входа 4</str> <!-- SID_SEL_GRP8_FLT4 -->
	</lang>
	<lang value="en">
		<str id="0"/>
		<str id="16">°C</str>
		<str id="17">К</str>
		<str id="18">F</str>
		<str id="32">MPa</str>
		<str id="33">kPa</str>
		<str id="34">kgf</str>
		<str id="35">bar</str>
		<str id="36">mbar</str>
		<str id="37">atm</str>
		<str id="38">mm Hg</str>
		<str id="39">psi</str>

		<str id="1000">temperature</str>
		<str id="1001">pressure</str>
		<str id="1002">period</str>

		<str id="1014">flowrate</str>
	</lang>
</strings>
